name: 'getharley'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

vars:
  surrogate_key_treat_nulls_as_empty_strings: true

models:
  getharley:
    +schema: wh
    staging:
      +schema: wh_staging
      +materialized: view
    intermediate:
      +schema: wh_intermediate
      +materialized: view
    marts:
      +schema: wh
      +materialized: table
